name: Test libexpat on Windows

on:
  push:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      MSYS_NO_PATHCONV: 1
      MSYS2_ARG_CONV_EXCL: "*"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Presubmit Repos
        run: |
          bazel --output_user_root=C:/_b run //tools:setup_presubmit_repos -- --module libexpat@2.8.3

      - name: Build and Test libexpat
        run: |
          cd temp_test_repos/libexpat/2.8.3/anonymous_module
          bazel --output_user_root=C:/_b build -- @libexpat
          bazel --output_user_root=C:/_b test --copt=-DXML_TESTING -- @libexpat//:expat_tests
